ARG cpprestsdk_version=latest
FROM cpprestsdk_debug:${cpprestsdk_version}

WORKDIR /app

# Argument for number of cores to use while building
ARG num_cores

COPY CMakeLists.txt ./CMakeLists.txt
COPY src ./src

RUN mkdir build.debug \
  && cd build.debug \
  && cmake .. -DCMAKE_BUILD_TYPE=Debug \
  && make -j ${num_cores}

COPY run_module.sh /run_module.sh
RUN dos2unix /run_module.sh

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y gdb vim \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir /app/output

WORKDIR /app/bin

ENTRYPOINT ["/bin/bash", "/run_module.sh"]
