ARG mwe_service_version=1.0
FROM mwe_service_debug:${mwe_service_version}

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y valgrind \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY run_module_valgrind.sh /run_module_valgrind.sh
RUN dos2unix /run_module_valgrind.sh

WORKDIR /app/bin

ENTRYPOINT ["/bin/bash", "/run_module_valgrind.sh"]
