ARG tag=latest
FROM debian:${tag}

RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -f -y build-essential libcpprest-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY mwe_server.cpp ./mwe_server.cpp

RUN g++ -D_TURN_OFF_PLATFORM_STRING -O3 -DNDEBUG -std=c++11 -o mwe_server -lcpprest -lpthread -lcrypto -lboost_system mwe_server.cpp

ENTRYPOINT ["/app/mwe_server", "0.0.0.0"]
